branch-defaults:
  despliegue:
    environment: rastreo2
    group_suffix: null
environment-defaults:
  examen-rastreo-env:
    branch: null
    repository: null
  rastreo:
    branch: null
    repository: null
  rastreo2:
    branch: null
    repository: null
global:
  application_name: examen-rastreo
  branch: null
  default_ec2_keyname: dennis
  default_platform: Python 3.11
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
